. (Join-Path $PSScriptRoot Compare-SecOpenPort.ps1)
. (Join-Path $PSScriptRoot Compare-SecOpenPorts.ps1)
. (Join-Path $PSScriptRoot Get-SecOpenPorts.ps1)
. (Join-Path $PSScriptRoot Set-SecFireWallSettings.ps1)
. (Join-Path $PSScriptRoot Compare-SecWirelessNetworks.ps1)
. (Join-Path $PSScriptRoot Get-SecWirelessNetworks.ps1)